# Replit configuration file for Next.js application

# Main settings
entrypoint = ".next/standalone/start.sh"
hidden = ["node_modules", ".config", ".next"]

# Environment variables
[env]
PORT = "5000"
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
NEXT_PUBLIC_PORT = "5000"
NEXT_PUBLIC_HOSTNAME = "0.0.0.0"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_DOCS_PATH = "/Docs"
NEXT_PUBLIC_DOCS_ENABLED = "true"

# Run configuration
run = "cd .next/standalone && ./start.sh"

# Build configuration
[build]
command = "./build.sh"